# [START cloudrun_django_cloudmigrate_yaml_python]
steps:
  - id: "Build Container Image"
    name: buildpacksio/pack
    args: ["build", "${_IMAGE_NAME}", "--builder=gcr.io/buildpacks/builder"]

  - id: "Push Container Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}"]

  - id: "Collect staticfiles"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud run jobs execute collect-job \
          --region ${_REGION} \

options:
  dynamicSubstitutions: true

substitutions:
  _REGION: europe-west1
  _SERVICE_NAME: devsite
  _ARTIFACT_REGISTRY: cloud-run-source-deploy
  _IMAGE_NAME: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}

images:
  - "${_IMAGE_NAME}"
# [END cloudrun_django_cloudmigrate_yaml_python]
