# Generated by Django 5.2 on 2025-04-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_todoitem_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todoitem",
            name="status",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="finished_on",
            field=models.DateField(null=True),
        ),
    ]
