# Generated by Django 5.2 on 2025-04-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_remove_todoitem_status_todoitem_finished_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="finished_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
