# Generated by Django 5.2 on 2025-04-14 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_todoitem_finished_on"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="finished_on",
            new_name="completed_date",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="created_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
