# Generated by Django 5.2 on 2025-04-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_rename_finished_on_todoitem_completed_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="title",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
